<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nl_pageconfig"
 *
 * Auto generated by Extension Builder 2018-08-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Page Configuration',
    'description' => 'Page Configuration by netzlabor coding GmbH',
    'category' => 'module',
    'author' => 'Maksym Chubin',
    'author_email' => 'maksim.chubin@netzlabor-coding.de',
    'state' => 'alpha',
    'version' => '2.1.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
