<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nl_pageconfig"
 *
 * Auto generated by Extension Builder 2018-08-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Page Configuration',
    'description' => 'Page Configuration by netzlabor coding GmbH',
    'category' => 'module',
    'author' => 'Maksym Chubin',
    'author_email' => 'maksim.chubin@netzlabor-coding.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
